Add site for Andreas
lindhe/lindhe.github.io pull request #2
Opened 2018-02-03 13:40 UTC by ErikThorsell

Now there are no excuses.

Fixes #1

2018-02-03 15:07 UTC, lindhe commented
Duplicate of #1

2018-02-03 15:08 UTC, lindhe commented
Sorry, not a duplicate. Will review tomorrow.

2018-02-04 20:29 UTC, lindhe requested changes
Yeah you are not removing the License. Amend your commit and I'll look at it again.

2018-02-05 08:00 UTC, ErikThorsell commented
Done.

2018-06-05 18:34 UTC, lindhe commented
@ErikThorsell how do I preview it before merging?

2018-06-18 19:07 UTC, lindhe commented
@ErikThorsell I just created a `development` branch. If you create a PR to that instead, I'll merge it.

2018-06-19 06:53 UTC, ErikThorsell commented
Providid information is sufficient.
Closing.

2018-06-19 06:53 UTC, closed without merging